### ISSUE TITLE
Reveal Animation Not Working on Lollipop 5.0.1

### ISSUE THREAD

**Issue by azfaarks** [Suleiman19/Android-Material-Design-for-pre-Lollipop#11]
Hello,
Reveal Animation is not working on Lollipop 5.0.1 although it is working on below versions but not working on 5.0.1 tested with HTC one with 5.0.1 & Nexus 5 with same 5.0.1.

If anyone facing the same problem please let me know and resolve this issue as soon as possible.

**Comment by Suleiman19** [comment]
Issue has been fixed. Take a look at RevealAnimation.java
There is a workaround for it.
