### ISSUE TITLE
Cannot build app in android studio..resource not found error

### ISSUE THREAD

**Issue by Im-PJ** [Suleiman19/Android-Material-Design-for-pre-Lollipop#12]
I have directly imported your package in android studio but it gives several errors on build. This is one of such error:
Error:(18, 58) No resource found that matches the given name (at 'drawable' with value '@drawable/abc_btn_check_to_on_mtrl_015').

this is my app build.gradle..other projects with similar gradle file works fine
    buildToolsVersion '23.0.0'
    compileSdkVersion 23
        minSdkVersion 10
        targetSdkVersion 23
    compile 'com.android.support:design:23.0.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.android.support:cardview-v7:23.0.0'
    compile 'com.android.support:palette-v7:23.0.0'
    compile 'com.github.ozodrukh:CircularReveal:1.1.0'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'

**Comment by Suleiman19** [comment]
Clean project and rebuild it for me. Or File> Invalidate Caches and restart. If it still doesn't work, then let me know.

**Comment by Im-PJ** [comment]
Did that several times. just importing the project gives me error without any changes to it.

**Comment by Im-PJ** [comment]
after downloading the repository as zip and importing in android studio it worked. Its crazy sometimes.
Thanks for this template. Can you also show how to maintain single nav drawer throughout app like for multiple activities. or should I use single activity with nav drawer and multiple fragments for content. Any material guideline for this scenario.

**Comment by Suleiman19** [comment]
With the new support library versions, a lot of these default resource references are now marked private.
Which means you can no longer reference them. Pass in your own Drawable resource to fix the issue.

For maintaining a Navigation Drawer across activities, make those Activities extend DrawerActivity.

**Comment by snetts** [comment]
How do I get ActionBar to work for my app? I am using API 23 and all my action bars have disappeared.

**Comment by Suleiman19** [comment]
@snetts You need to use the new Toolbar widget. You can check any of my Activity files to see how its done.

**Comment by snetts** [comment]
Thanks @Suleiman19 . Let me get this Toolbar working.
