### ISSUE TITLE
how to scroll viewpager with its tab ? 

### ISSUE THREAD

**Issue by engr-erum** [Suleiman19/Android-Material-Design-for-pre-Lollipop#13]
hi i have xml layout in which i have Linearlayout (iMAGEVIE and some buttons) + design tablayout+ viewpager now i want once user start scrol down viewpager fragments then the whole page inclusing Linearlayout (iMAGEVIE and some buttons) + design tablayout  will scroll towards up and when user start scrolling up then all tabs adn linear will be visible @Suleiman19

**Comment by Suleiman19** [comment]
Could you please post a screenshot for the purpose of clarity?

**Comment by engr-erum** [comment]
http://imgur.com/rLwG76Q @Suleiman19  here is the image i want below the tabs there may bbe gridview or listview inside fragments once i start scrolling listview then the whole above layout including tabs showuld go up and when i scroll down then this will scroll down right now i am just able toscroll only listview after the tabs ..... once i start scroll it should scroll whle layout so that i can get more space for my  contents

**Comment by Suleiman19** [comment]
The guidelines indicate a Quick Return pattern for the Toolbar alone and not for the Tabs. Hence the Tabs would still remain visible on scroll. If you still want to implement that, then I suggest you go through this post: http://blog.grafixartist.com/implement-floating-action-button-fab-part-2/
The only logic you need to tweak here is, scroll distance must be (Toolbar height) + (Tabs height)

Also, don't use the issues section to ask a question unless its not a problem. You got StackOverflow. Post there and I'd be happy to help.
