### ISSUE TITLE
hide toolbar and remain tabStrip

### ISSUE THREAD

**Issue by MohsenShafiee** [Suleiman19/Android-Material-Design-for-pre-Lollipop#14]
hi thanks for this sample :)
i'm using a viewpager in my main activity! and some nested fragments in my pager!
is it possible to hide toolbar when recyclerView scrolled but remain the viewPager tabStrip?
somthing like google play just take a look how it hides the toolbar...
thanks...

**Comment by Suleiman19** [comment]
Yes, that's possible. Simply add a TabLayout below your Toolbar. Use the new Design Support Library widgets and wrap both of them within AppBarLayout. 

Set these scroll flags on your Toolbar to enable the hiding:

``` java
app:layout_scrollFlags="scroll|enterAlways|snap"
```
