### ISSUE TITLE
Does it not work with AppCompat 23?

### ISSUE THREAD

**Issue by razi429** [Suleiman19/Android-Material-Design-for-pre-Lollipop#15]
Getting many errors like the one shown below, when I try to compile this project having target=android-23

res\layout\recyclerlist_item.xml:2: error: No resource identifier found for attribute 'cardElevation' in package 'com.suleiman.material'

Please help! Newbie here :)

**Comment by Suleiman19** [comment]
I'm using v23.1.1 the latest support libraries and face no such issues.
Provide your own dimen value for the card elevation like this:

``` xml
 app:cardElevation="2dp"
```
