### ISSUE TITLE
TabLayout onclick does not change the page

### ISSUE THREAD

**Issue by arushijain45** [Suleiman19/Android-Material-Design-for-pre-Lollipop#17]
In TabsAnimation, once we swipe pages from first to last and then click on first tab, the indicator move to first tab but fragment does not change.

**Comment by Suleiman19** [comment]
I'm currently using support library v23.1.1 
The key lies in this:

``` java
tabLayout.setupWithViewPager(viewPager);
```

Remove the clickListener for the TabLayout.
