### ISSUE TITLE
How To make the list items Clickable 

### ISSUE THREAD

**Issue by mamakar333** [Suleiman19/Android-Material-Design-for-pre-Lollipop#18]
I need to start a new activity by clicking on one of the list items.Please provide any code regarding this.It would be a lot of helpful to me

**Comment by ghost** [comment]
simply just add <b> ItemClickListener </b> then Get position and start your new activity

This Link May Be Usefull : http://paste.ubuntu.com/14128748/

**Comment by Suleiman19** [comment]
@mamakar333  go through this adapter. The MainActivity uses this to detect clicks.
https://github.com/Suleiman19/Android-Material-Design-for-pre-Lollipop/blob/master/MaterialSample/app/src/main/java/com/suleiman/material/adapter/SimpleRecyclerAdapter.java
