### ISSUE TITLE
Fragment creation under TabAnimationActivity.java

### ISSUE THREAD

**Issue by headuck** [Suleiman19/Android-Material-Design-for-pre-Lollipop#4]
I think the proper way for fragment instance creation in real code may be within the getItem method of the FragmentPagerAdapter? In the current TabAnimationActivity.java new fragments got created each time when there is a rotation.  This may work fine in some Android versions but under Android 5 which I tested, however, the system may be retaining the fragments (and does not call getItem again). This results in leaks and errors.

**Comment by Suleiman19** [comment]
Agree with that @headuck, however the purpose of TabAnimationActivity is to demonstrate how the Tab widgets in the Design support library work.

**Comment by headuck** [comment]
Yes, but since lazy people like me might be using this as a starting point for further development and only realize the more proper way to create fragments afterwards, perhaps a short comment or two in appropriate places might save someone's efforts in future.

**Comment by Suleiman19** [comment]
Feel free to change that in a pull request and I'll look it over.
