### ISSUE TITLE
Question: How stretch tablayout text by length? #5

### ISSUE THREAD

**Issue by Radzhab** [Suleiman19/Android-Material-Design-for-pre-Lollipop#5]
![screenshot 2](https://cloud.githubusercontent.com/assets/2556411/8350795/3a3cc50e-1b31-11e5-8790-18be67f65145.jpg)
i use similar project. But cannot understand how my text not full showing

**Comment by Suleiman19** [comment]
Try using 

``` java
tabLayout.setTabMode (TabLayout.MODE_SCROLLABLE);
```

This allows all Tabs' text to take the required width. So the obvious trade-off is the entire TabLayout will be scrollable.

**Comment by Radzhab** [comment]
thx man)

**Comment by Suleiman19** [comment]
Glad you got it done :+1:
