### ISSUE TITLE
Can't import and build

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Suleiman19/Android-Material-Design-for-pre-Lollipop#9]
How could this be?
This is what I get:

![untitled20150805095402](https://cloud.githubusercontent.com/assets/5357526/9079944/faa0ab30-3b57-11e5-9bc6-d1220c795909.png)

**Comment by Suleiman19** [comment]
I've never had this issue before. Not sure what's causing it. Try invalidating cache and restart. Then re import a fresh copy of the project.

**Comment by AndroidDeveloperLB** [comment]
how do i do that?

**Comment by Suleiman19** [comment]
First remove the project. Then File> Invalidate Caches/ Restart

**Comment by AndroidDeveloperLB** [comment]
It didn't help. Still the same issue.

**Comment by kamilwlf** [comment]
I have the same problem

**Comment by Suleiman19** [comment]
Go to your Properties> Build> Gradle and use default gradle wrapper. I tried downloading and importing from here. This is how I solved my issue.

**Comment by Suleiman19** [comment]
I've updated all build configs and libraries from my side and pushed changes. Should be resolved now.
